import type { Metadata } from "next";
import { Lora, Source_Sans_3 } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

// Lora — serif used for headings and the header wordmark. Variable font, so
// it covers the design's 500/600/700 weights (plus italic) without listing each.
const lora = Lora({
  variable: "--font-lora",
  subsets: ["latin"],
  style: ["normal", "italic"],
  display: "swap",
});

// Source Sans 3 — sans-serif used for body copy, nav, and buttons.
const sourceSans = Source_Sans_3({
  variable: "--font-source-sans",
  subsets: ["latin"],
  display: "swap",
});

// Site-wide defaults. These are what the HOME page uses (app/page.tsx sets no
// metadata of its own) and what any future page inherits if it forgets to.
// Until 2026-07-23 these were still the create-next-app placeholders, which
// meant the home page's browser tab and Google result both read
// "Create Next App" / "Generated by create next app".
export const metadata: Metadata = {
  title: "Roots of Knowledge Tutoring — Reading Tutoring for K–5 in Los Angeles",
  description:
    "Culturally responsive reading tutoring for children in grades K–5 across underserved Los Angeles County communities — free to qualifying families. In person and online.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${lora.variable} ${sourceSans.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Header />
        <main style={{ flex: 1 }}>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
