import type { Metadata } from "next";
import { Lora, Source_Sans_3 } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

// Lora — serif used for headings and the header wordmark. Variable font, so
// it covers the design's 500/600/700 weights (plus italic) without listing each.
const lora = Lora({
  variable: "--font-lora",
  subsets: ["latin"],
  style: ["normal", "italic"],
  display: "swap",
});

// Source Sans 3 — sans-serif used for body copy, nav, and buttons.
const sourceSans = Source_Sans_3({
  variable: "--font-source-sans",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${lora.variable} ${sourceSans.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Header />
        <main style={{ flex: 1, display: "flex", flexDirection: "column" }}>
          <div style={{ marginTop: "auto", marginBottom: "auto", width: "100%", display: "flex", flexDirection: "column", flex: 1 }}>
            {children}
          </div>
        </main>
        <Footer />
      </body>
    </html>
  );
}
